
###################
# Jekyll Settings #
###################
markdown: rdiscount
permalink: /:categories/:year-:month-:day/:title
pagecontent: 50

#################
# Site Settings #
#################

title : Easy!Developer
tagline: Site Tagline
author :
  name : wata.smile
  email : まだ（2018.2~）
  github : developer-2018
  twitter : まだ（2018.2~）
  facebook : まだ（2018.2~）

link:
  twitter : 
  facebook : 
  github : https://github.com/developer-2018

